<?php
return [
  'surnames' => [
    ['趙', 'Chiu'],
    ['錢', 'Chin'],
    ['孫', 'Suen'],
    ['李', 'Lee'],
    ['周', 'Chau'],
    ['吳', 'Ng'],
    ['鄭', 'Cheng'],
    ['王', 'Wong'],
    ['馮', 'Fung'],
    ['陳', 'Chan'],
    ['褚', 'Chu'],
    ['衛', 'Wai'],
    ['蔣', 'Cheung'],
    ['沈', 'Shum'],
    ['韓', 'Hon'],
    ['楊', 'Yeung'],
    ['朱', 'Chu'],
    ['秦', 'Chun'],
    ['尤', 'Yau'],
    ['許', 'Hui'],
    ['何', 'Ho'],
    ['呂', 'Lui'],
    ['施', 'Sze'],
    ['張', 'Cheung'],
    ['孔', 'Hung'],
    ['曹', 'Cho'],
    ['嚴', 'Yim'],
    ['華', 'Wah'],
    ['金', 'Kam'],
    ['魏', 'Ngai'],
    ['陶', 'Tao'],
    ['姜', 'Chiang'],
    ['戚', 'Chik'],
    ['謝', 'Tse'],
    ['鄒', 'Chau'],
    ['喻', 'Yu'],
    ['柏', 'Pak'],
    ['水', 'Sui'],
    ['竇', 'Tau'],
    ['章', 'Cheung'],
    ['雲', 'Wan'],
    ['蘇', 'So'],
    ['潘', 'Poon'],
    ['葛', 'Ko'],
    ['奚', 'Kai'],
    ['范', 'Fan'],
    ['彭', 'Pang'],
    ['郎', 'Long'],
    ['魯', 'Lo'],
    ['韋', 'Wai'],
    ['昌', 'Cheung'],
    ['馬', 'Ma'],
    ['苗', 'Miu'],
    ['鳳', 'Fung'],
    ['花', 'Fa'],
    ['方', 'Fong'],
    ['俞', 'Yu'],
    ['任', 'Yam'],
    ['袁', 'Yuen'],
    ['柳', 'Lau'],
    ['酆', 'Fung'],
    ['鮑', 'Pau'],
    ['史', 'Sze'],
    ['唐', 'Tong'],
    ['費', 'Fai'],
    ['廉', 'Lim'],
    ['岑', 'Shum'],
    ['薛', 'Sit'],
    ['雷', 'Lui'],
    ['賀', 'Ho'],
    ['倪', 'Ngai'],
    ['湯', 'Tong'],
    ['滕', 'Tang'],
    ['殷', 'Yan'],
    ['羅', 'Law'],
    ['畢', 'Pat'],
    ['郝', 'Hao'],
    ['鄔', 'Woo'],
    ['安', 'On'],
    ['常', 'Sheung'],
    ['樂', 'Lok'],
    ['於', 'Yu'],
    ['時', 'See'],
    ['傅', 'Fu'],
    ['皮', 'Pei'],
    ['卞', 'Pin'],
    ['齊', 'Chi'],
    ['康', 'Hong'],
    ['伍', 'Ng'],
    ['余', 'Yu'],
    ['元', 'Yuen'],
    ['卜', 'Pu'],
    ['顧', 'Koo'],
    ['孟', 'Mang'],
    ['平', 'Ping'],
    ['黃', 'Wong'],
    ['和', 'Wo'],
    ['穆', 'Mu'],
    ['蕭', 'Shiu'],
    ['尹', 'Wan']
  ],
  'chnGivenNames' => [
    [
      '二牛',
      '小明',
      '大明',
      '偉文',
      '小輝'
    ],
    [
      '小花',
      '二索',
      '小麗'
    ]
  ],
  'engGivenNames' => [
    [
      'JAMES',
      'JOHN',
      'ROBERT',
      'MICHAEL',
      'WILLIAM',
      'DAVID',
      'RICHARD',
      'CHARLES',
      'JOSEPH',
      'THOMAS',
      'CHRISTOPHER',
      'DANIEL',
      'PAUL',
      'MARK',
      'DONALD',
      'GEORGE',
      'KENNETH',
      'STEVEN',
      'EDWARD',
      'BRIAN',
      'RONALD',
      'ANTHONY',
      'KEVIN',
      'JASON',
      'MATTHEW',
      'GARY',
      'TIMOTHY',
      'JOSE',
      'LARRY',
      'JEFFREY',
      'FRANK',
      'SCOTT',
      'ERIC',
      'STEPHEN',
      'ANDREW',
      'RAYMOND',
      'GREGORY',
      'JOSHUA',
      'JERRY',
      'DENNIS',
      'WALTER',
      'PATRICK',
      'PETER',
      'HAROLD',
      'DOUGLAS',
      'HENRY',
      'CARL',
      'ARTHUR',
      'RYAN',
      'ROGER',
      'JOE',
      'JUAN',
      'JACK',
      'ALBERT',
      'JONATHAN',
      'JUSTIN',
      'TERRY',
      'GERALD',
      'KEITH',
      'SAMUEL',
      'WILLIE',
      'RALPH',
      'LAWRENCE',
      'NICHOLAS',
      'ROY',
      'BENJAMIN',
      'BRUCE',
      'BRANDON',
      'ADAM',
      'HARRY',
      'FRED',
      'WAYNE',
      'BILLY',
      'STEVE',
      'LOUIS',
      'JEREMY',
      'AARON',
      'RANDY',
      'HOWARD',
      'EUGENE',
      'CARLOS',
      'RUSSELL',
      'BOBBY',
      'VICTOR',
      'MARTIN',
      'ERNEST',
      'PHILLIP',
      'TODD',
      'JESSE',
      'CRAIG',
      'ALAN',
      'SHAWN',
      'CLARENCE',
      'SEAN',
      'PHILIP',
      'CHRIS',
      'JOHNNY',
      'EARL',
      'JIMMY',
      'ANTONIO',
      'DANNY',
      'BRYAN',
      'TONY',
      'LUIS',
      'MIKE',
      'STANLEY',
      'LEONARD',
      'NATHAN',
      'DALE',
      'MANUEL',
      'RODNEY',
      'CURTIS',
      'NORMAN',
      'ALLEN',
      'MARVIN',
      'VINCENT',
      'GLENN',
      'JEFFERY',
      'TRAVIS',
      'JEFF',
      'CHAD',
      'JACOB',
      'LEE',
      'MELVIN',
      'ALFRED',
      'KYLE',
      'FRANCIS',
      'BRADLEY',
      'JESUS',
      'HERBERT',
      'FREDERICK',
      'RAY',
      'JOEL',
      'EDWIN',
      'DON',
      'EDDIE',
      'RICKY',
      'TROY',
      'RANDALL',
      'BARRY'
    ],
    [
      'Mary',
      'Ann',
      'Linda',
      'Barbara',
      'Elizabeth',
      'Jennifer',
      'Maria',
      'Margaret',
      'Dorothy',
      'Lisa',
      'Nancy',
      'Karen',
      'Betty',
      'Helen',
      'Sandra',
      'Carol',
      'Sharon',
      'Sarah',
      'Kimberly',
      'Angela',
      'Amy',
      'Breanda',
      'Anna',
      'Laura',
      'Amanda',
      'Christine',
      'Marie',
      'Janet',
      'Catherine',
      'Joyce',
      'Diane',
      'Alice',
      'Julie',
      'Teresa',
      'Doris',
      'Gloria'
    ]
  ]
];